### ISSUE TITLE
Option to disable livereload?

### ISSUE THREAD

**Issue by AtroxDev** [petecoop/generator-express#101]
I would love to have a option to disable the generation of the gulp livereload "task".
If this is wanted, I'd love to try to add this.

Thanks,
Atrox

**Comment by petecoop** [comment]
Suppose you could if you wanted, I like it but suppose it's not for everyone.

It could be part of #78 which will be checkbox options rather than it's own prompt

**Comment by AtroxDev** [comment]
Correct, this Issue can be closed. Just add this to #78.

Thanks,
Atrox

**Comment by petecoop** [comment]
Actually I'll create a separate issue as #78 is more to do with modules rather than settings
