### ISSUE TITLE
Optional settings

### ISSUE THREAD

**Issue by petecoop** [petecoop/generator-express#102]
As #78 but for more "preference" settings:
- Option to remove livereload see #101

**Comment by Atrox** [comment]
@petecoop I'm nearly done with #101, I'm just currently stuck at the ejs template... 

What is the best way to remove livereload there? Because I'm not able to use the options there. Extra set of templates or should I just disable this option for ejs?

Thanks,
Atrox

**Comment by petecoop** [comment]
Hey @Atrox thanks for doing this I've lagged behind a bit with the planned features!

With regards to ejs, see https://github.com/petecoop/generator-express/blob/master/app/index.js#L216

iirc I've had to use `bulkDirectory` to stop it from trying to run the templating within ejs, it's a bit annoying really. I think the best would probably be to do some string replacement on header.ejs once it's been copied, either that or have an alternative header.ejs for when livereload is off and rename/delete one depending on the option
