### ISSUE TITLE
Build Task

### ISSUE THREAD

**Issue by vikz91** [petecoop/generator-express#103]
I recently installed this generator and unable to find the build task. Any pointers?

**Comment by petecoop** [comment]
Build task?

**Comment by vikz91** [comment]
Hi,
I am srry I've put it in very short way. What I was looking for, was the final build package after minification (like generator-angular provides) that I can put in production server.  After reading the source, it seems there is no such task. So, putting the whole generated app ( with grunt) on the production server is ok?

**Comment by petecoop** [comment]
I've left deployment process up to you really - I haven't done anything to push anyone in a particular way. What I'm more focused on is the development experience of getting set up ready to go on something as quick as possible. If you've any recommendations on what I could do to make the deployment process better then I'm open to it.

At the moment the only resource that needs to be built is the css, if you choose it - you can easily pre-process this by running e.g. `gulp sass`. However I've left the settings to default - which means they don't usually minify themselves but it'd be easy enough to change those settings if you look at the relevant docs for that gulp/grunt plugin.

I see your point that putting some resources on the server e.g. Gruntfile etc is pointless - that's up to you and your deploy process really - it won't be publicly accessible to anyone as it's not in your public dir.
