### ISSUE TITLE
yo express failed in Mac OSX

### ISSUE THREAD

**Issue by undefinedN** [petecoop/generator-express#104]
I just installed express app generator and it has installed successfully but when I run it, I am getting error like below  

`
/usr/local/lib/node_modules/generator-express/node_modules/yeoman-generator/lib/base.js:445
this.env.sharedFs.on('change', writeFiles);
^TypeError: undefined is not a function
`

Thanks

**Comment by petecoop** [comment]
see #94

**Comment by sebringj** [comment]
#94 is on windows, not mac. Its not working for me either on my osx mac el capitan v10.11

**Comment by petecoop** [comment]
doesn't look like a windows specific issue, @sebringj have you tried the solution on #94? are you using npm@3?

**Comment by sebringj** [comment]
my npm is 3.3.9 and I'm on node v4.2.0

**Comment by sebringj** [comment]
it may have something to do with my nvm   that's probably it   I can only install the generator-aspnet locally as the npm install package -g flag doesn't actually place things in node_modules. But local generator-aspnet does "work" but results in the /node_modules/yeoman-generator/lib/base.js:466
  this.env.sharedFs.on('change', writeFiles);  TypeError: this.env.sharedFs.on is not a function

**Comment by petecoop** [comment]
others have had issues with nvm: #135 it sounds like something out of the project - a dependency not working with npm@3 yet or local configuration
