### ISSUE TITLE
Shouldn't a new folder be created by default, or at least prompted as an option?

### ISSUE THREAD

**Issue by russjr08** [petecoop/generator-express#109]
I'm pretty new to Yeoman, so I'm not sure what the default (if any) conventions are. I however think that it'd make more sense to create a new folder for the generated project, or at least prompt the user if they want to output to a new folder / the current one, as I may or may have not just ran yo express in my projects folder...

**Comment by petecoop** [comment]
Yeah I think this would be a nice option, I don't personally use any other generators so not sure what the norms are there either

**Comment by petecoop** [comment]
In 2.7.0 there's now an option to create a new directory
