### ISSUE TITLE
Default project run fails

### ISSUE THREAD

**Issue by russjr08** [petecoop/generator-express#110]
I'm trying to run a default MVC CoffeeScript project, but the coffee compiler fails on app/models/article.coffee

[This is the default generated article.coffee file](https://gist.github.com/russjr08/e6c25f6d97122560c4e5), it looks like templating stuff was left in the output? I don't recognize <% and %> as regular CoffeeScript syntax.

After removing the template stuff, it fails because 'Article' was not a defined variable. Was it supposed to be ArticleSchema?

Edit: Okay, so a var just has to be assigned to the mongoose.model call, or export that directly.

**Comment by petecoop** [comment]
Yeah looks like there's an issue in the coffee generator, will look into it
