### ISSUE TITLE
pg-hstore dependency is missing

### ISSUE THREAD

**Issue by leonprou** [petecoop/generator-express#111]
Selecting the PostreSQL I get the following error:

>     throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
 Error: The dialect postgres is not supported. (Error: Cannot find module 'pg-hstore')

Adding pg-hstore to dependencies solving this issue

**Comment by petecoop** [comment]
Thanks will get this sorted, think this is something new with Sequelize 2.0
