### ISSUE TITLE
Add instructions to create own directory first

### ISSUE THREAD

**Issue by bluepuma77** [petecoop/generator-express#120]
I would be great to add to the "Getting started" instructions, that you should create a directory first and "cd" into it. I thought it will behave like "git clone" and create a directory, which is not the case. Now I have the generated files directly in my home directory, mixed with all kinds of other files.

**Comment by bluepuma77** [comment]
Cleanup, in case someone else did the mistake:
```
mkdir express-generated
mv bower.json express-generated/
mv package.json express-generated/
mv .bowerrc express-generated/
mv .gitignore express-generated/
mv app.js express-generated/
mv app/controllers/home.js express-generated/
mv app/models/article.js express-generated/
mv config/config.js express-generated/
mv config/express.js express-generated/
mv app/views/error.ejs express-generated/
mv app/views/footer.ejs express-generated/
mv app/views/header.ejs express-generated/
mv app/views/index.ejs express-generated/
mv public/css/style.scss express-generated/
mv gulpfile.js express-generated/
```

**Comment by petecoop** [comment]
when I created this - this behaviour seemed to be the default with other yeoman generators. I intend to make some changes see #109

**Comment by petecoop** [comment]
In 2.7.0 there's now an option to create a new directory.
