### ISSUE TITLE
Object [object Promise] has no method 'success'

### ISSUE THREAD

**Issue by Gtskk** [petecoop/generator-express#123]
Object [object Promise] has no method 'success' in app\controllers\home.js:10:24

I think changing 'success' to 'done' should work.

**Comment by petecoop** [comment]
Correct method is actually `.then()` it appears `.success()` and `.done()` were deprecated as part of the 2.0 release of sequelize.

**Comment by petecoop** [comment]
thanks for finding and posting the issue, have fixed this and published as 2.7.1
