### ISSUE TITLE
Gulp replace timeout reload

### ISSUE THREAD

**Issue by petecoop** [petecoop/generator-express#128]
Better method here: https://github.com/vohof/gulp-livereload/blob/master/examples/nodemon/gulpfile.js

**Comment by stereobooster** [comment]
Tried it, doesn't work for me (does not reload browser). But existing solutions doesn't work for me either: it reloads browser, but server isn't started yet

**Comment by petecoop** [comment]
hi yeah I've implemented this on another project and works nicely apart from that solution doesn't pipe stderr, will be adding this sometime soon
