### ISSUE TITLE
RethinkDB Connection IP addresses..

### ISSUE THREAD

**Issue by abitt** [petecoop/generator-express#129]
Is it possible to change the IP address you connect to if you're using RethinkDB in the generator? I've edited the ./node_modules/thinky/config.js but alas it only connects to localhost still.

Where exactly are the configuration options for it?

**Comment by petecoop** [comment]
you shouldn't be editing stuff in `node_modules`. The config is in `config/config.js`, there's a `db` section, you'll just need to change the options following [this guide](http://thinky.io/documentation/api/thinky/) - think you're just looking for the `host` option
