### ISSUE TITLE
global installation of generator-express does not work

### ISSUE THREAD

**Issue by ahmadferdous** [petecoop/generator-express#135]
According to documentation, I first installed the generator **globally** by doing `npm install generator-express -g`.
Then I did `yo express` and got the following error:
```
Error express 

You don't seem to have a generator with the name express installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
```
Later I installed `generator-express` **locally** instead of globally and then ran `yo express`. It worked.

Is the documentation updated? or it actually works with npm global installation?

**Comment by petecoop** [comment]
It should work like that, it's how generators are installed in yeoman's documentation [here](http://yeoman.io/learning/index.html), it's how I use it. Did you get any errors when installing globally?

**Comment by ahmadferdous** [comment]
No, global installation went fine.
Do you think it may have anything to do with node.js being installed using `nvm`?

**Comment by petecoop** [comment]
This sounds more like issues with system config than an issue with the project itself, so closing
