### ISSUE TITLE
How to auto open browser?

### ISSUE THREAD

**Issue by zhouhao27** [petecoop/generator-express#148]
When I run **gulp**, the server started, but the browser is not opened automatically. Is that supported in this generator? Thanks.

**Comment by zhouhao27** [comment]
I did the following:

1. Install gulp-open

> npm i gulp-open --save-dev

2. Add a gulp task

   gulp.task('open', function(){
     var options = {
       uri: 'localhost:3000'
     };
     gulp.src(__filename)
      .pipe(open(options));
    });

    gulp.task('default', [
      'sass',
      'develop',
      'watch',
      'open'
   ]);

But the browser is still not opened automatically.

**Comment by petecoop** [comment]
No it isn't supported in the generator, might try it out sometime - I'm guessing though if you restart gulp it will open a new window?

I don't think this is really an issue for me - the use of gulp-open should be brought up with who ever makes gulp-open
