### ISSUE TITLE
sass task wrong path

### ISSUE THREAD

**Issue by Klemensas** [petecoop/generator-express#155]
Ran default configuration, choose basic,  nunjucks, sass, gulp.
When running gulp sass task I'm getting:
> [23:46:39] Using gulpfile C:\comely-leds\gulpfile.js
> [23:46:39] Starting 'sass'...
> [23:46:39] '""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
> [23:46:39] Finished 'sass' after 77 ms

I haven't changed any of the configurations. Why woud it try to use such a path?

**Comment by petecoop** [comment]
I can't replicate the issue, I'm not sure why it's going into `C:\Program`, looks to be an issue specific to gulp-sass or node-sass

**Comment by Klemensas** [comment]
Yes, I've isolated the issue to gulp-ruby-sass package, going to replace it with gulp-sass.
