### ISSUE TITLE
Remove bower usage, get it all from npm

### ISSUE THREAD

**Issue by mikeerickson** [petecoop/generator-express#156]
Just did a fresh install this morning (love this project)

Have you gave thought to removing bower support and use npm for everything?   If interested, I can do a PR on this task

**Comment by petecoop** [comment]
As far as I know bower is still preferred for front-end dependencies

**Comment by petecoop** [comment]
Actually nothing is even installed from bower, it's just setup as `.bowerrc` and `bower.json` files, so the choice is 100% up to the user.
