### ISSUE TITLE
Unhandled rejection Error: SequelizeConnectionError: password authentication failed for "dbuser"

### ISSUE THREAD

**Issue by nitetrik** [petecoop/generator-express#163]
Got this error when using Postgresql, the password and username were correct, could it be something to do with the the pg_hba.conf?  This is for the MVC with Postgresql option.

**Comment by nitetrik** [comment]
Solved it it was issue with Node Postgres not being able to handle symbols in passwords.

**Comment by petecoop** [comment]
Ah okay, btw for anything like this check the docs for the library it uses: http://docs.sequelizejs.com/en/latest/
