### ISSUE TITLE
Recommended body-parser validation?

### ISSUE THREAD

**Issue by LordWingZero** [petecoop/generator-express#165]
I find myself doing this a lot in my handlers:

``` Javascript
router.post('/login', function(req, res, next) {
  if (_.isEmpty(req.body.username) || _.isEmpty(req.body.password)) {
    return res.render('login', {
      login_error: loginFailed
    });
  }
});
```

Is this the best option right now https://www.npmjs.com/package/express-validation? or is it overkill?

**Comment by petecoop** [comment]
I'd recommend [express-validator](https://www.npmjs.com/package/express-validator)
