### ISSUE TITLE
npm WARN deprecated native-or-bluebird@1.2.0: please use 'any-promise' instead

### ISSUE THREAD

**Issue by VictorioBerra** [petecoop/generator-express#168]
I get this when running ```npm install -g generator-express```.

**Comment by nitetrik** [comment]
Its just a deprecation warning, few dependencies need updating.

**Comment by petecoop** [comment]
The deprecation warning comes from `spawn-sync`, which is a dependency of `cross-spawn` which is a dependency of `yeoman-generator` - which is at the latest version, there's nothing I can do until it's resolved down the chain.
