### ISSUE TITLE
Generator Express without template engine?

### ISSUE THREAD

**Issue by THCloud** [petecoop/generator-express#174]
Hi,
I'm trying to use this generator to do something. But a problem confused me for several days.

Can generator-express provide a new version without template engine?

I wanna use simple HTML files for my angular's route.js, and I don't wanna put these HTML files to 
express.static(). That will make me ... uncomfortable.

Any solutions?

**Comment by petecoop** [comment]
This was actually started a while ago and not finished in a PR here: #108. You could take a look there and see how they did it, it'd be great if someone were to pick this up and finish it!

What makes you uncomfortable about putting your HTML in `express.static()`? It'd need to be publicly available somehow

**Comment by THCloud** [comment]
Hi，
Thanks for your reply
If put HTMLs in `express.static()`, it means you can visit this HTML by input the file path in browser, isn't it?

**Comment by THCloud** [comment]
I think that's what make me uncomfortable...I think the browser should only show your current state or route, but not your file path, that's why I wanna use angular's route

**Comment by THCloud** [comment]
I got a repo that solved my problem.

**Comment by petecoop** [comment]
Right but you still need to serve the document so angular can load it?

**Comment by wuno** [comment]
@THCloud  you said you have a repo that solved the problem? Can you tell us what you did? I would like to serve my index.html without a template engine as well. But I keep getting weird errors like when the page refresh etc.
