### ISSUE TITLE
couldn't start gulp following instructions with coffee no database and marko

### ISSUE THREAD

**Issue by drdamour** [petecoop/generator-express#180]
node v6.2 
--coffee 
gulp
mvc
marko
less
no database

run gulp get

```
/lametric-air-now/node_modules/coffee-script/lib/coffee-script/coffee-script.js:234
      throw helpers.updateSyntaxError(err, stripped, filename);
      ^

/lametric-air-now/app/controllers/home.coffee:9:1: error: unexpected indentation
    indexTemplate.render
^^^^
```

fixed that whitespacing and get some more weird stuff...here's how it started

https://github.com/drdamour/lametric-air-now/blob/343f9563234154d8f1a66ade291c2c97ccb23a80/app/controllers/home.coffee

**Comment by petecoop** [comment]
Hey thanks for reporting this, apologies it's taken me this long to get to. It's fixed in the latest version - 2.12.1
