### ISSUE TITLE
Jade to Pug?

### ISSUE THREAD

**Issue by ghost** [petecoop/generator-express#190]

**Comment by petecoop** [comment]
Yeah will make the change, have been notified it before but from what I could see everything was still jade

**Comment by andysaini** [comment]
Ok, closing it for now.

**Comment by petecoop** [comment]
It should be open as it needs doing!

**Comment by hurricaneMitch** [comment]
Any chance ^this^ can get pulled?

**Comment by petecoop** [comment]
Still waiting on pug 2 to come out of beta, see the discussion on the PR. #191

**Comment by willsteinmetz** [comment]
@hurricaneMitch hopefully soon. It's been in development for quite a while.

**Comment by willsteinmetz** [comment]
Just an update...they're still taking 5ever on releasing Pug to stable. One day when it comes out, I'll update the PR.

**Comment by petecoop** [comment]
Yeah I checked recently too

**Comment by sigmasoldi3r** [comment]
Like this proposal 👍

**Comment by willsteinmetz** [comment]
Since it's kind of taking fiveever for an official release to come out (I did the exploratory branch 7 months ago O_O), do we still want to wait for the official release or update the PR from August and then update the version when 2.0 officially comes out in 2019 (I'm kidding...I hope)?

**Comment by petecoop** [comment]
The branch will need updating, but I'd wait until 2.0 is actually out

**Comment by gaoshijun1993** [comment]
2.0 has been out ,so please update it.....

**Comment by petecoop** [comment]
It's not out it's in release candidate

**Comment by navdeepio** [comment]
Please convert it to pug already :)

**Comment by willsteinmetz** [comment]
Oh look, it has FINALLY been released.

**Comment by petecoop** [comment]
wow took a long time (https://github.com/pugjs/pug/releases/tag/pug%402.0.0)

**Comment by navdeepio** [comment]
looks like you forgot about it again xD @petecoop

**Comment by willsteinmetz** [comment]
After this issue being open for almost two years, I think PR #191 is finally ready.

![Hold onto your butts](https://media.giphy.com/media/OCu7zWojqFA1W/giphy.gif)

**Comment by petecoop** [comment]
Thanks for coming back and doing this @willsteinmetz, very nearly close to actually get this finished!

![](https://media.giphy.com/media/oYmYj4FUVZPlS/giphy.gif)
