### ISSUE TITLE
sudo npm install -g generator-express:node postinstall

### ISSUE THREAD

**Issue by cybibo** [petecoop/generator-express#192]
> spawn-sync@1.0.15 postinstall /Users/ryan/.node/lib/node_modules/generator-express/node_modules/yeoman-generator/node_modules/yeoman-test/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall

|
|

> node postinstall

generator-express@2.12.2 /Users/ryan/.node/lib/node_modules/generator-express
├── underscore.string@3.3.4 (util-deprecate@1.0.2, sprintf-js@1.0.3)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.5, minimatch@3.0.3)
└── yeoman-generator@0.23.4 (detect-conflict@1.0.1, read-chunk@1.0.1, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, rimraf@2.5.4, async@1.5.2, text-table@0.2.0, class-extend@0.1.2, user-home@2.0.0, xdg-basedir@2.0.0, dargs@4.1.0, pretty-bytes@3.0.1, nopt@3.0.6, istextorbinary@1.0.2, error@7.0.2, cli-table@0.3.1, debug@2.2.0, find-up@1.1.2, path-exists@2.1.0, run-async@2.2.0, chalk@1.1.3, cross-spawn@3.0.1, through2@2.0.1, mem-fs-editor@2.3.0, shelljs@0.7.3, read-pkg-up@1.0.1, github-username@2.1.0, dateformat@1.0.12, gruntfile-editor@1.2.0, yeoman-assert@2.2.1, download@4.4.3, yeoman-environment@1.6.3, yeoman-test@1.4.0, html-wiring@1.2.0, lodash@4.15.0)

**Comment by petecoop** [comment]
What's the issue?

**Comment by cybibo** [comment]
ryan-Mac:generator-express ryan$ yo express
Error express 
You don't seem to have a generator with the name express installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name]

**Comment by petecoop** [comment]
Try `yo doctor`

**Comment by cybibo** [comment]
$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!

**Comment by nodejquery11** [comment]
Cybibo, I also face many issue to install the express-generator but unable to install it. Then later I check *.byte and install accordingly and now I m able to run it.
I guess, u r using Unix or Linux system so plzz check the version and install to delete all earlier files. Might it will help u.
