### ISSUE TITLE
How to run Production mode with grunt?

### ISSUE THREAD

**Issue by JaosnHsieh** [petecoop/generator-express#197]
I've been using 'yo express' command and choose MVC , jade , grunt ....
Everything is working fine and now I'm managing to deploy my app.
Now I only know two commands to start my app

 1. grunt
 2. node app.js

If I run "grunt" command on my production server , it will enable livereload server , which is good for development but not production.

I think maybe grunt can help me to do optimization but I couldn't find it. I saw webpack is a good choice but it's too difficult for me to use it.

Is there any way to do optimization ( like compress js css ) or other tasks for deploying on my 'yo express' generated app?

Thanks.

**Comment by petecoop** [comment]
Generally you don't want to use grunt or gulp for running things in production, you want to use `node app.js`, but use something to monitor the process and restart it if it fails etc, a nice tool for this is [pm2](https://github.com/Unitech/pm2).

For compressing js, css you could have a build step as part of your deploy, depending on which css pre-processor you are using you should already be able to add the option to make a compressed version in the gruntfile - if you look at the docs for those tools.

Hope this helps

**Comment by JaosnHsieh** [comment]
I got it.
Use grunt or gulp build compressed js , css files... and monitor process it with pm2.

Cheers , petecoop
