### ISSUE TITLE
babel integration with front end?

### ISSUE THREAD

**Issue by harryio** [petecoop/generator-express#203]

**Comment by petecoop** [comment]
There's no front-end js in this at all, do whatever you like!

**Comment by harryio** [comment]
I meant gulp integration for es6 compilation!

**Comment by petecoop** [comment]
I'm not going to include front-end stuff in this, while I do use babel myself there's a lot more choices that comes with that e.g. use browserify, webpack, rollup? babel latest, or preset-2 or 2015?

I want to keep this strictly back-end, I believe there are plenty of people that don't want all that stuff, and I want to keep this maintainable
