### ISSUE TITLE
Create model, controller, view from command line

### ISSUE THREAD

**Issue by zhouchengkho** [petecoop/generator-express#207]
Hi
I created a project with this generator and is actually working well, but is there any way I can create model, controller, view from command line? I used the angular generator before, see [https://github.com/yeoman/generator-angular] . The good things by using "yo angular:controller someController" to create your controller instead of manually adding a js file in the project is I don't have to write a correspondent js file in test folder. So I was wondering if it's possible to run a command like: "yo express:controller someController" or something similar to create these files from command line? Or is there already is a way I just don't know?

Thanks

**Comment by petecoop** [comment]
Hey, no this isn't something that you can currently do but I agree it would be a nice addition

**Comment by zhouchengkho** [comment]
@petecoop ok cool thanks
