### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nodejquery11** [petecoop/generator-express#209]
Hi All,
While installing the `express generator`, I was receiving an error and unable to install in my system. For your reference please find an error screen shot and debug log file
Require assistance.

[npm-debug.zip](https://github.com/petecoop/generator-express/files/737355/npm-debug.zip)

![error_express_generator](https://cloud.githubusercontent.com/assets/18608441/22402481/72c8756c-e61e-11e6-86f1-0e7e83d43831.jpg)

Windows: 10
Node Version: v6.9.4
npm version: 4.1.1

**Comment by petecoop** [comment]
Did you try running again as Administrator? Are you able to install anything with npm?

**Comment by nodejquery11** [comment]
Yes, I am able to install npm module in same folder. I would like to say that laptop is mine and I didn't define any Admin in my system.
However, I am myself `admin` in my-system :)

**Comment by petecoop** [comment]
can you install anything globally? e.g. `npm install -g yo`

**Comment by petecoop** [comment]
Probably worth looking at NPM's troubleshooting: https://github.com/npm/npm/wiki/Troubleshooting
