### ISSUE TITLE
Can not set username and password for MySql

### ISSUE THREAD

**Issue by SubhashisPK** [petecoop/generator-express#220]
Where can I set username and password for MySql ?

**Comment by petecoop** [comment]
something like: `mysql://username:password@host/db`

**Comment by SubhashisPK** [comment]
Yes

**Comment by SubhashisPK** [comment]
I think, we should add MySQL credentials at config.js file from config folder, After generating new project, i got error like: 
Unhandled rejection Error: SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'110.227.108.221' (using passw
ord: NO)

**Comment by petecoop** [comment]
Just change the credentials?
