### ISSUE TITLE
could not find this query: ---- Executing (default): SELECT `id`, `title`, `url`, `text`, `createdAt`, `updatedAt` FROM `Articles` AS `Article`;

### ISSUE THREAD

**Issue by santanubankura** [petecoop/generator-express#221]

**Comment by petecoop** [comment]
This is just example code, it's here: https://github.com/petecoop/generator-express/blob/master/app/templates/mvc/app/controllers/home.js#L19

**Comment by santanubankura** [comment]
How to write MySQL query -app/controller/home.js
& app/controller/model/artical.js

**Comment by petecoop** [comment]
It uses sequelize as the ORM, have a look at the docs
