### ISSUE TITLE
Deprecate Bower

### ISSUE THREAD

**Issue by chennighan** [petecoop/generator-express#226]
Can you deprecate bower and move to yarn?

**Comment by petecoop** [comment]
I thought about this recently. Currently it doesn't install any bower dependencies, just sets up the configuration which I may remove.

On yarn I think this is more of a preference, so may be an option to choose between yarn and npm - I use yarn myself but some prefer npm with it's recent advances.

**Comment by chennighan** [comment]
Right, I think it's only a matter of time before npm just implements the features yarn has. One thing you may also want to consider is running the bower install before npm install as it will break if the user doesn't already have bower installed sometimes.
