### ISSUE TITLE
Remove Ruby Sass support in favor of only Node Sass

### ISSUE THREAD

**Issue by willsteinmetz** [petecoop/generator-express#230]
Looking at the install instructions on the Sass site https://sass-lang.com/install , the Ruby gem isn't even mentioned anymore. The first install option mentioned is actually the Node Sass version via npm.

Given that, I think it makes sense to remove the code for Ruby Sass and rename the Node Sass option to just Sass or Sass (Node) in the options list during generation. The plus with this is it makes a little bit less stuff to maintain and keeps the package up to date.

**Comment by petecoop** [comment]
Good! The Ruby gem was always such a pain
