### ISSUE TITLE
How to use sequelize association in your pattern ?  

### ISSUE THREAD

**Issue by TangMonk** [petecoop/generator-express#73]
In app/models folder, I have following models

```
airport.coffee
user.coffee
```

The airport.coffee has one user:

```coffeescript
module.exports = (sequelize, DataTypes) ->

  Airport = sequelize.define 'Airport',
    name: DataTypes.STRING
    device_id: DataTypes.STRING

  Airport.hasOne User, {as: 'publisher'}
  Airport.hasOne User, {as: 'reviewer'}
  Airport.hasOne User, {as: 'templater'}
```

But it not work. 

thanks for your help :D

**Comment by petecoop** [comment]
Hey, I'll be honest I think I've overlooked this and it needs an update to work properly.

[Here's an article on how it should work](http://sequelizejs.com/articles/express). I'll create an update uses this pattern soon...

**Comment by TangMonk** [comment]
@petecoop  thanks !
