### ISSUE TITLE
does gulp test start server?

### ISSUE THREAD

**Issue by timmyg** [petecoop/generator-express#82]
I keep getting the following when I try to make a request in one of my tests...
```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

gulpfile.js
```
gulp.task('test', function () {
    gulp.src('test/**/*.coffee')
        .pipe(mocha({
            compilers: 'coffee:coffee-script/register'
        }))
});
```

tests.coffee
```
describe "test that test architecture is working", ->
  
	it "basic test", (done) ->
		assert 0 is 0
		done()

	it "passes2", (done) ->
		request.get
			url: "http://localhost:3000/"
		, (error, response, body) ->
			console.log error if error
			assert response.statusCode is 200
			done()
```

**Comment by petecoop** [comment]
Do you have the server running first by using `gulp`? This will just run everything with the task of `default`, so think to get what you want to achieve you need to have `gulp` running in one terminal then run `gulp test` in another.

Going to close this issue as it's really nothing to do with the generator and entirely your code...

**Comment by timmyg** [comment]
Ok, i guess I was wondering if there was a way to run tests without also running the server in another window (i.e. have 'gulp test' start server, run tests, stop server) as I am not super familiar with gulp/grunt. Awesome generator BTW, well done!

**Comment by petecoop** [comment]
Ah, sure if you create a gulp task like `gulp.task('runtest', ['develop', 'test'])` it will start the server first then run your test, I think you'll then have to stop it manually.

Alternatively you could add the develop task to your test task as a dependency e.g. `gulp.task('test', ['develop'], function...`
