### ISSUE TITLE
TypeError: this.env.sharedFs.on('change', writeFiles); undefined is not a function

### ISSUE THREAD

**Issue by jmlivingston** [petecoop/generator-express#94]
I just tried running this generator for the first time, but got the following error: 

Versions
Yeoman: 1.4.5
generator-express: 2.5.1
Environment: Windows 8.1

![image](https://cloud.githubusercontent.com/assets/1093719/6429112/84a39c2c-bf73-11e4-9bd3-f2800bc03c2d.png)

**Comment by petecoop** [comment]
`npm generator-express -version` will actually print npm's version number, try:
```
npm list generator-express -g
```
To print out the version of generator-express

**Comment by petecoop** [comment]
Found a [similar issue](https://github.com/Swiip/generator-gulp-angular/issues/363) they suggest re-installing yo, maybe try re-install the generator too: `npm install -g yo generator-express`

**Comment by jmlivingston** [comment]
That did the trick! Great work by the way. Exactly what I was looking for.

**Comment by jmlivingston** [comment]
Closing the issue.

**Comment by petecoop** [comment]
Thanks!
